---
- name: Check if bucket exists
  shell: "mc ls {{ mc_alias }}/{{ bucket_item.name }}"
  register: bucket_check
  ignore_errors: true


# 1. Oddiy bucket yaratish
- name: Create normal bucket (no versioning, no object lock)
  shell: "mc mb {{ mc_alias }}/{{ bucket_item.name }}"
  when:
    - bucket_check.rc != 0
    - (bucket_item.versioning is not defined or not bucket_item.versioning)
    - (bucket_item.object_lock is not defined or not bucket_item.object_lock)
  register: create_bucket_normal
  ignore_errors: true


# 2. Object Lock bilan bucket yaratish
- name: Create bucket with Object Lock
  shell: "mc mb --with-lock {{ mc_alias }}/{{ bucket_item.name }}"
  when:
    - bucket_check.rc != 0
    - bucket_item.object_lock is defined
    - bucket_item.object_lock | bool
  register: create_bucket_lock
  ignore_errors: true


# 3. Versioning yoqish (yaratilgan bucketda)
- name: Enable versioning on bucket
  shell: "mc version enable {{ mc_alias }}/{{ bucket_item.name }}"
  when:
    - bucket_item.versioning is defined
    - bucket_item.versioning | bool
  register: enable_versioning
  ignore_errors: true


# 4. Quota qo‘shish (agar mavjud bo‘lsa)
- name: Set quota for bucket
  shell: "mc quota set {{ mc_alias }}/{{ bucket_item.name }} --size {{ bucket_item.quota }}"
  when:
    - bucket_item.quota is defined
    - bucket_item.quota | length > 0
  register: set_quota
  ignore_errors: true


# 5. Process policies (mavjud kod)
- name: Process policies
  include_tasks: policy.yml
  loop: "{{ (user.policy is string) | ternary([user.policy], user.policy) }}"
  loop_control:
    loop_var: policy_item
