- block:
    - name: Set user policy file and actions
      set_fact:
        policy_file: "/tmp/{{ user.user | lower }}_policy_{{ policy_item | lower }}.json"
        policy_name: "{{ user.user | lower }}_policy_{{ policy_item | lower }}"
        actions: >-
          {% if user.policy == 'r' %}
          ["s3:GetObject"]
          {% elif user.policy == 'rw' %}
          ["s3:GetObject", "s3:PutObject", "s3:ListBucket"]
          {% elif user.policy == 'rwd' %}
          ["s3:GetObject", "s3:PutObject", "s3:DeleteObject", "s3:ListBucket"]
          {% else %}
          ["s3:GetObject"]
          {% endif %}
      tags: policy

    - name: Write user-specific policy JSON
      copy:
        dest: "{{ policy_file }}"
        content: |
          {
            "Version": "2012-10-17",
            "Statement": [ {
              "Effect": "Allow",
              "Action": {{ actions }},
              "Resource": [
                {% for b in user.bucket %}
                  "arn:aws:s3:::{{ b }}/*",
                  "arn:aws:s3:::{{ b }}"
                  {% if not loop.last %},{% endif %}
                {% endfor %}
              ]
            } ]
          }
      tags: policy

    - name: Create policy for {{ user.user }}
      ansible.builtin.shell: >
        mc admin policy create {{ mc_alias }} {{ policy_name }} {{ policy_file }}
      ignore_errors: true
      tags: policy

    - name: Attach {{ policy_name }} to {{ user.user }}
      ansible.builtin.shell: >
        mc admin policy attach {{ mc_alias }} --user {{ user.user }} {{ policy_name }}
      ignore_errors: true
      tags: policy
